site:
  title: Adailson - Timeline
  description: Bem vindo ao meu site
personal:
  name: Adailson Aguiar
  avatar: https://github.com/adailsonaguiar.png
  socialNetworks:
    youtube: https://www.youtube.com/@UFCBR
    github:  https://github.com/adailsonaguiar
 
